# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_api: <%= ENV["POSTMARK_API_KEY"] %>
  email_provider_username: <%= ENV["POSTMARK_API_KEY"] %>
  email_provider_password: <%= ENV["POSTMARK_API_KEY"] %>
  domain_name: https://rails-postmark.herokuapp.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  personal_owner_email: <%= ENV["PERSONAL_OWNER_EMAIL"] %>
  secret_key_base: 91e4949079616f7bb42532dce50f64c82223fb1da82d2a165a404239e3315af457756b93d427243ebb0e78614d307b7abfb517223aca13f86edfffd5e1114d1b

test:
  secret_key_base: 009811ff935a39a4e909c7fe56d87e671a09a30b937e1ce37f9b4cf527cde33ebae6f206020050ec81b224755130cad67cc2ecd5c07933271cce4ce3f9746869

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
